// ============================================================
// THE SAIL METHOD — owners + 5 chapters
// ============================================================
export const OWNERS = {
  SD: { label: 'SD', full: '销售设计 Sales Designer', color: '#8B6F4E' },
  SS: { label: 'SS', full: '现场主管 Site Supervisor', color: '#5C7A4A' },
  WH: { label: 'WH', full: '仓储 Warehouse', color: '#A8896B' },
  PU: { label: '采购', full: '采购 Purchasing', color: '#6B5D4F' },
};

export const STAGES = [
  {
    code: 'A',
    name: 'VISION',
    nameCN: '洞察',
    framework: 'BOND',
    label: '客户洞察 + 建立信任',
    en: 'Discovery & Trust',
    tagline: 'Listen first. Understand the home before designing.',
    taglineCN: '先聆听 — 在动笔之前，理解整个家。',
    owner: 'SD',
    days: '销售前',
    linkedForm: 'SPACE_SURVEY',
    formGate: 'A3',
    gates: [
      { id: 'A1', short: 'BOND-1 Begin', label: '首次接触 + 客户档案建档', en: 'First contact + profile' },
      { id: 'A2', short: 'BOND-2 Observe', label: '展厅接待 + 现场感知', en: 'Showroom + initial site visit' },
      { id: 'A3', short: 'BOND-3 Need', label: '客户空间问卷 (28题) 完成', en: 'Space Survey completed' },
      { id: 'A4', short: 'BOND-4 Deposit', label: '定金到账 + 双方签字', en: 'Deposit + sign-off' },
    ],
  },
  {
    code: 'B',
    name: 'BLUEPRINT',
    nameCN: '制图',
    framework: '4S',
    label: '深化设计 + 精准复尺',
    en: 'Design & Re-measurement',
    tagline: 'Design with precision. Every millimeter measured.',
    taglineCN: '以精度为准 — 每一毫米都丈量过。',
    owner: 'SD',
    days: '1-2 周',
    linkedForm: 'MEASUREMENT',
    formGate: 'B2',
    gates: [
      { id: 'B1', short: '4S-1 Start', label: 'Kickoff: 项目编号 + 群 + 文件夹', en: 'Project ID + group + folder' },
      { id: 'B2', short: '4S-2 Survey', label: '现场量尺核查表 (20项) 完成', en: 'Site Measurement done' },
      { id: 'B3', short: '4S-3 Sign', label: '图纸签核 (未签不下单)', en: 'Drawing sign-off' },
      { id: 'B4', short: '4S-4 Source', label: '下 PO + 锁交期 + 风险标注', en: 'PO placed + timeline locked' },
    ],
  },
  {
    code: 'C',
    name: 'CRAFT',
    nameCN: '匠造',
    framework: '3M',
    label: '生产监控 + 客户透明',
    en: 'Production with Transparency',
    tagline: 'Crafted, not assembled. Quality monitored weekly.',
    taglineCN: '匠造 — 不是装配。每周质量复检。',
    owner: 'PU',
    days: '4-8 周',
    gates: [
      { id: 'C1', short: '3M-Site', label: 'Monitor Site: 工地状态每周更新', en: 'Site weekly update' },
      { id: 'C2', short: '3M-Product', label: 'Monitor Product: 生产节点 + 交期', en: 'Production schedule' },
      { id: 'C3', short: '3M-Customer', label: 'Monitor Customer: 下一步告知', en: 'Customer next-step comms' },
    ],
  },
  {
    code: 'D',
    name: 'ARRIVAL',
    nameCN: '就位',
    framework: '5O + 5T',
    label: '到货核查 + 安装跟踪',
    en: 'Arrival & Installation',
    tagline: 'Installed with care. On time, on plan.',
    taglineCN: '精心安装 — 按时按图，万无一失。',
    owner: 'SS',
    days: '1-3 周',
    linkedForm: 'INSTALL_QC',
    formGate: 'D5',
    gates: [
      { id: 'D1', short: '5O-Product', label: '点货 + 开箱 + 分单标签', en: 'Product inspection' },
      { id: 'D2', short: '5O-Site', label: 'Site Ready 复检', en: 'Site re-check' },
      { id: 'D3', short: '5O-Payment', label: '付款 + 入住日期 + DO 确认', en: 'Payment + move-in + DO' },
      { id: 'D4', short: '5O-Logistics', label: '排车 + 安装队期', en: 'Truck + crew scheduled' },
      { id: 'D5', short: '5T-Install', label: '安装质量检查表 (20项) 完成', en: 'Install QC done' },
      { id: 'D6', short: '5T-Quality', label: 'Punch List 全部关单', en: 'Punch list cleared' },
    ],
  },
  {
    code: 'E',
    name: 'SIGNATURE',
    nameCN: '落款',
    framework: '5H',
    label: '验收交付 + 长期关系',
    en: 'Handover & Legacy',
    tagline: 'Sign off only when 100% satisfied.',
    taglineCN: '客户百分百满意时，才是真正的交付。',
    owner: 'SS',
    days: '1-2 天',
    linkedForm: 'HANDOVER',
    formGate: 'E1',
    gates: [
      { id: 'E1', short: '5H-Product', label: '最终验收表 (16项) 全过', en: 'Final Handover form Pass' },
      { id: 'E2', short: '5H-Protection', label: '成品保护 (膜/护角)', en: 'Product protection' },
      { id: 'E3', short: '5H-Site', label: '现场可使用状态', en: 'Site ready for use' },
      { id: 'E4', short: '5H-Briefing', label: '使用 + 保养讲解 + 视频', en: 'Briefing + video' },
      { id: 'E5', short: '5H-Reputation', label: '评价 / 转介绍 动作', en: 'Review / referral' },
    ],
  },
];

// Client-facing simplified language (for ClientShareView)
export const CLIENT_STAGES = {
  A: { label: 'Vision · 洞察', desc: '我们倾听您的生活方式与收纳需求' },
  B: { label: 'Blueprint · 制图', desc: '深化设计与现场精准量尺' },
  C: { label: 'Craft · 匠造', desc: '工厂排程生产与品质把控' },
  D: { label: 'Arrival · 就位', desc: '货物运抵与专业团队安装' },
  E: { label: 'Signature · 落款', desc: '完工验收与长期售后关怀' },
};
