// =====================================================================
// Sail CRM — Seed data
// Pre-loaded sample leads from Wilson's daily report. Only used when the
// database is empty (first-run experience). Production users should
// import their real Excel data via the Import button.
// =====================================================================

import { excelDate, initDesignFlow } from './utils.js';
import { STAGE_MIGRATION, WON_STAGES, COMPLETE_STAGE } from './constants.js';

const RAW = [
  { pic: 'Sheerly', clientType: 'ZXL', leadSource: 'ZXL', firstContactedDate: excelDate(45962), date: excelDate(46043), clientName: 'ZXL - Melawati', contactMethod: 'Whatsapp', contactNo: '019-6071919', region: 'Tmn Melawati', soNumber: 'SO-B00005', priority: '1. High (Confirmed)', salesStage: 'Stage 5: Shipping & Installation', quotationAmount: 260000, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: 'Before CNY 2026', isDecisionMaker: '', nextAction: 'Active Action: Follow up status of production and shipping', statusRemarks: 'Items onboard, estimated 9/2 arrived port' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Referral', firstContactedDate: excelDate(45999), date: excelDate(46052), clientName: 'Kong', contactMethod: 'Whatsapp', contactNo: '017-2559976', region: 'Bangsar', soNumber: 'SO-B00007', priority: '1. High (Confirmed)', salesStage: 'Stage 5: Shipping & Installation', quotationAmount: 58587, paymentInfo: '50% 14/1/2026', clientNeeds: 'Whole House Customization', expectedDeliveryDate: 'End of March 2026', isDecisionMaker: '', nextAction: 'Active Action: Follow up status of production', statusRemarks: 'Done checking drawing, Done Payment' },
  { pic: 'Sheerly', clientType: 'ZXL', leadSource: 'ZXL', firstContactedDate: excelDate(45994), date: excelDate(46043), clientName: 'ZXL - Soon Yik', contactMethod: 'Whatsapp', contactNo: '019-6071919', region: 'Cyberjaya', soNumber: 'SO-B00010', priority: '1. High (Confirmed)', salesStage: 'Stage 6: Complete', quotationAmount: 5608, paymentInfo: '50% 23/12/2025', clientNeeds: '八百库', expectedDeliveryDate: 'Early March 2026', isDecisionMaker: '', nextAction: 'Active Action: Follow up status of production and shipping', statusRemarks: 'Items out of delivery, Sent out for courier shipment' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Referral', firstContactedDate: excelDate(45968), date: excelDate(46052), clientName: 'Andy', contactMethod: 'Whatsapp', contactNo: '012-4004982', region: 'Ara Damansara', soNumber: 'SO-B00011', priority: '1. High (Confirmed)', salesStage: 'Stage 6: Complete', quotationAmount: 29707, paymentInfo: '50% 23/12/2025', clientNeeds: 'TV Console, Book Shelf', expectedDeliveryDate: 'Early March 2026', isDecisionMaker: '', nextAction: 'Active Action: Follow up status of production and shipping', statusRemarks: 'Items out of delivery, Sent out for courier shipment' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Archidex', firstContactedDate: excelDate(46029), date: excelDate(46056), clientName: 'Arvindd', contactMethod: 'Whatsapp', contactNo: '019-2782387', region: 'Seremban', soNumber: 'SO-B00012', priority: '1. High (Confirmed)', salesStage: 'Stage 3: Design', quotationAmount: 71234, paymentInfo: '5% 4/2/2026', clientNeeds: 'Kitchen', expectedDeliveryDate: '', isDecisionMaker: 'Yes', nextAction: 'Passive Action: Waiting customer check appliance size', statusRemarks: 'Customer paid 5% deposit, doing 3D design' },
  { pic: 'Sheerly', clientType: 'ZXL', leadSource: 'ZXL', firstContactedDate: excelDate(45992), date: excelDate(46043), clientName: 'ZXL - Kensington', contactMethod: 'Whatsapp', contactNo: '019-6071919', region: 'Kensington', soNumber: 'SO-B00013', priority: '1. High (Confirmed)', salesStage: 'Stage 5: Shipping & Installation', quotationAmount: 82223, paymentInfo: '50% 6/2/2026', clientNeeds: 'Whole House Customization', expectedDeliveryDate: 'End of March 2026', isDecisionMaker: '', nextAction: 'Passive Action: Installation', statusRemarks: 'Issued SO to ZXL, factory checking drawings' },
  { pic: 'Wilson', clientType: 'Retail Customer', leadSource: 'Walk-in', firstContactedDate: excelDate(46031), date: excelDate(46091), clientName: 'Jun', contactMethod: 'Whatsapp', contactNo: '011-16363514', region: 'Puchong', soNumber: 'SO-B00014', priority: '1. High (Confirmed)', salesStage: 'Stage 4: Order & Start Production', quotationAmount: 20000, paymentInfo: '', clientNeeds: 'Foyer + Master bedroom', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Passive Action: Waiting customer check defect', statusRemarks: 'Key collection at 25/5' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Instagram', firstContactedDate: excelDate(46066), date: excelDate(46168), clientName: 'Mr See', contactMethod: 'Whatsapp', contactNo: '013-362 4361', region: 'Pavillion Damansara', soNumber: 'SO-B00015', priority: '1. High (Confirmed)', salesStage: 'Stage 3: Design', quotationAmount: 120000, paymentInfo: '', clientNeeds: 'Whole house', expectedDeliveryDate: '', isDecisionMaker: 'Yes', nextAction: 'Active Action: Revise design & prepare quotation', statusRemarks: '' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46103), date: excelDate(46113), clientName: 'En Jun', contactMethod: 'Whatsapp', contactNo: '016-568 9693', region: 'Glomac Damansara Residensi', soNumber: 'SO-B00016', priority: '1. High (Confirmed)', salesStage: 'Stage 3: Design', quotationAmount: 50000, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: Follow up design, meet up to go through detail, collect 2nd payment', statusRemarks: '' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46134), date: excelDate(46134), clientName: 'Win', contactMethod: 'Whatsapp', contactNo: '012-634 3680', region: "D'clover", soNumber: 'SO-B00017', priority: '1. High (Confirmed)', salesStage: 'Stage 3: Design', quotationAmount: 50000, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: Update design & give final quote', statusRemarks: '' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46121), date: excelDate(46121), clientName: 'Yangel', contactMethod: 'Whatsapp', contactNo: '016-216 3235', region: 'Setia Alam', soNumber: 'SO-B00018', priority: '1. High (Confirmed)', salesStage: 'Stage 3: Design', quotationAmount: 70000, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: Follow up design', statusRemarks: 'July, August will collect key' },
  { pic: 'Reina', clientType: 'Retail Customer', leadSource: 'Instagram', firstContactedDate: excelDate(46136), date: excelDate(46136), clientName: 'Bell', contactMethod: 'Whatsapp', contactNo: '013-265 8803', region: 'M Adora', soNumber: 'SO-B00019', priority: '1. High (Confirmed)', salesStage: 'Stage 3: Design', quotationAmount: 32000, paymentInfo: '', clientNeeds: 'Kitchen + Master Bedroom + Yard', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Passive Action: Waiting customer check appliance size', statusRemarks: '' },
  { pic: 'Reina', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46103), date: excelDate(46113), clientName: 'Deeb', contactMethod: 'Whatsapp', contactNo: '', region: 'PJ', soNumber: 'SO-B00020', priority: '1. High (Confirmed)', salesStage: 'Stage 3: Design', quotationAmount: 0, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: Provide mood board', statusRemarks: '' },
  { pic: 'Reina', clientType: 'Retail Customer', leadSource: 'Instagram', firstContactedDate: excelDate(46136), date: excelDate(46136), clientName: 'Sean To', contactMethod: 'Whatsapp', contactNo: '016-327 3972', region: 'Kapar', soNumber: 'SO-B00021', priority: '1. High (Confirmed)', salesStage: 'Stage 3: Design', quotationAmount: 25000, paymentInfo: '', clientNeeds: 'Kitchen + Master Bedroom', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: Update design & give final quote', statusRemarks: '' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46123), date: excelDate(46136), clientName: 'Slavin Khoo', contactMethod: 'Whatsapp', contactNo: '016-328 8488', region: 'Timur Tuai', soNumber: 'SO-B00022', priority: '1. High (Confirmed)', salesStage: 'Stage 2: Visited Showroom & Quoted', quotationAmount: 65000, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: Site Meeting', statusRemarks: 'Budget customer, max will be 50k budget' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Rednote', firstContactedDate: excelDate(46012), date: excelDate(46085), clientName: 'Mr Lim (中国夫妇)', contactMethod: 'Wechat', contactNo: 'IamfineNMX', region: 'KL', soNumber: 'SO-B00008', priority: '2. High (Potential)', salesStage: 'Stage 3: Design', quotationAmount: 92695, paymentInfo: '设计费 2/12/2025', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: 'Yes', nextAction: 'Active Action: Ask for 50% Deposit', statusRemarks: '10/2/2026 Told customer estimated amount after meeting, waiting respond' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'From Sail China', firstContactedDate: excelDate(45956), date: excelDate(46043), clientName: 'Ms Chuah 蔡', contactMethod: 'Whatsapp', contactNo: '012-3397511', region: 'The Mines', soNumber: 'SO-B00009', priority: '2. High (Potential)', salesStage: 'Stage 3: Design', quotationAmount: 375249, paymentInfo: '', clientNeeds: 'Kitchen', expectedDeliveryDate: 'June 2026', isDecisionMaker: 'Yes', nextAction: 'Active Action: Follow up design, collect 2nd payment', statusRemarks: '' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46134), date: excelDate(46134), clientName: 'Mr Lau', contactMethod: 'Whatsapp', contactNo: '', region: 'Muar', soNumber: '', priority: '2. High (Potential)', salesStage: 'Stage 2: Visited Showroom but No Quote', quotationAmount: 0, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: To start 3D design', statusRemarks: '' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Walk-in', firstContactedDate: excelDate(46103), date: excelDate(46135), clientName: 'Lynne', contactMethod: 'Whatsapp', contactNo: '016-449 1134', region: 'Setia Alam', soNumber: '', priority: '3. Medium', salesStage: 'Stage 1: New Contact', quotationAmount: 0, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: '', statusRemarks: '24/4 have contact Sheerly, to arrange appointment' },
  { pic: 'Wilson', clientType: 'Retail Customer', leadSource: 'Referral', firstContactedDate: excelDate(46099), date: excelDate(46099), clientName: 'Mr Ong, Mr Andrew', contactMethod: 'Whatsapp', contactNo: '', region: 'Subang', soNumber: '', priority: '3. Medium', salesStage: 'Stage 2: Visited Showroom & Quoted', quotationAmount: 80000, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: Waiting Response', statusRemarks: 'Self Built house' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46121), date: excelDate(46136), clientName: 'Min Min Ching', contactMethod: 'Whatsapp', contactNo: '016-216 3235', region: 'Kota Kemuning', soNumber: '', priority: '3. Medium', salesStage: 'Stage 2: Visited Showroom & Quoted', quotationAmount: 120000, paymentInfo: '', clientNeeds: 'Dedaun Rimba (Shah Alam)', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Passive Action: To send regular message', statusRemarks: 'July, August will collect key' },
  { pic: 'Reina', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46099), date: excelDate(46099), clientName: 'Zyon Design', contactMethod: 'Whatsapp', contactNo: '', region: '', soNumber: '', priority: '3. Medium', salesStage: 'Stage 2: Visited Showroom but No Quote', quotationAmount: 0, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: Prepare Quotation', statusRemarks: 'Interior Designer' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Facebook', firstContactedDate: excelDate(46123), date: excelDate(46123), clientName: 'Brenda', contactMethod: 'Whatsapp', contactNo: '019-264 5533', region: 'Bon Kiara, Mont Kiara', soNumber: '', priority: '3. Medium', salesStage: 'Stage 2: Visited Showroom but No Quote', quotationAmount: 70000, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: '', nextAction: 'Active Action: To prepare quotation & mood board', statusRemarks: 'Potential, getting key in July' },
  { pic: 'Sheerly', clientType: 'Retail Customer', leadSource: 'Walk-in', firstContactedDate: excelDate(45805), date: excelDate(46043), clientName: 'Alex Lim', contactMethod: 'Whatsapp', contactNo: '010-7976785', region: 'Setia Alam Eco Park', soNumber: '', priority: '4. Low', salesStage: 'Stage 2: Visited Showroom but No Quote', quotationAmount: 0, paymentInfo: '', clientNeeds: 'Whole House Customization', expectedDeliveryDate: '', isDecisionMaker: 'Yes', nextAction: 'Active Action: Preparing 3D design', statusRemarks: '' },
];

export const initialLeads = RAW.map((l, i) => {
  const now = new Date().toISOString();
  const salesStage = STAGE_MIGRATION[l.salesStage] || l.salesStage;
  return {
    ...l,
    salesStage,
    id: `seed_${Date.now()}_${i}`,
    createdAt: now,
    updatedAt: now,
    stageEnteredAt: now,
    homeAddress: '',
    afterSales: [],
    handoverDriveLink: '',
    followUp: null,
    designFlow: salesStage === 'Stage 3: Design' ? initDesignFlow() : null,
    signedDetailDrawing: WON_STAGES.includes(salesStage),
    signedHandoverList: salesStage === COMPLETE_STAGE,
    history: [{
      timestamp: now,
      user: 'System',
      type: 'created',
      message: `Lead seeded from initial data`,
    }],
  };
});
